# Generated by Django 4.2.6 on 2023-10-18 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="leave",
            name="reason_of_leave",
            field=models.TextField(
                help_text="Provide a brief description of the reason for the leave.",
                null=True,
                verbose_name="Reason of name",
            ),
        ),
    ]
