# Generated by Django 4.2.6 on 2023-10-18 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_leave_reason_of_leave"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category_of_leave",
            name="name",
            field=models.CharField(
                choices=[
                    ("Casual_Leave", " Casual Leave"),
                    ("Earned_Leave", " Earned Leave"),
                    ("Sick_Leave", " Sick Leave"),
                    ("Sick_Leave_LOP", " Sick Leave-LOP"),
                    ("Marraige_Leave", " Marraige Leave"),
                ],
                default="Casual_Leave",
                max_length=50,
            ),
        ),
    ]
