# Generated by Django 4.2.6 on 2023-10-18 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_alter_category_of_leave_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryOfLeave",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("total_number", models.IntegerField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name="leave",
            name="category_of_leave",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.categoryofleave",
            ),
        ),
        migrations.DeleteModel(name="Category_of_leave",),
    ]
