# Generated by Django 4.2.6 on 2023-10-19 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0004_categoryofleave_alter_leave_category_of_leave_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="do_joining",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="dob",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="salary",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
