# Generated by Django 4.2.6 on 2023-10-19 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0005_alter_user_do_joining_alter_user_dob_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leave",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
