# Generated by Django 4.2.6 on 2023-10-20 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0006_alter_leave_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leave",
            name="application_status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                ],
                default="Pending",
                max_length=50,
            ),
        ),
    ]
