# Generated by Django 4.2.6 on 2023-10-25 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0007_alter_leave_application_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leave",
            name="duration_of_leave",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
