# Generated by Django 4.2.6 on 2023-11-02 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0009_alter_leave_end_date_alter_leave_start_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="leave",
            name="application_status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                ],
                default="Pending",
                max_length=50,
                verbose_name="Update Application Status",
            ),
        ),
    ]
